"""empty message

Revision ID: bc83de885d26
Revises: c48984af0825
Create Date: 2022-05-28 01:32:05.128774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc83de885d26'
down_revision = 'c48984af0825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recycle_item', sa.Column('item_subimage', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recycle_item', 'item_subimage')
    # ### end Alembic commands ###
