"""empty message

Revision ID: c48984af0825
Revises: c0fcb974f29e
Create Date: 2022-05-27 23:29:31.152373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48984af0825'
down_revision = 'c0fcb974f29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recycle_item', sa.Column('size', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recycle_item', 'size')
    # ### end Alembic commands ###
