"""empty message

Revision ID: eb3060cad183
Revises: 2eaa6babbfdf
Create Date: 2022-05-28 04:17:30.659482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3060cad183'
down_revision = '2eaa6babbfdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recycle_item', sa.Column('count', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recycle_item', 'count')
    # ### end Alembic commands ###
